baseurl = "/"
languageCode = "en-us"
title = "My New Hugo Site"

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 0

[[menu.main]]
    name = "About"
    url  = "about"
    weight = 5

[[menu.main]]
    name = "Blog"
    url  = "post/"
    weight = 10
